### ISSUE TITLE
NOTE: (for people who cannot install Chrome extensions (i.e. on a school chromebook))

### ISSUE THREAD

**Issue by RuralAnemone** [LibreScore/dl-musescore#1]
If you cannot install tampermonkey on your device, just make a bookmarklet with this code as the "link":

`javascript:(function () {let code = document.createElement('script');code.src = 'https://github.com/LibreScore/dl-musescore/releases/latest/download/dl-musescore.user.js';document.body.appendChild(code);}())`

**Comment by RuralAnemone** [comment]
or you can also use Xmader's earlier version if you need other file types:
`javascript:(function () {let code = document.createElement('script');code.src = 'https://msdl.librescore.org/install.user.js';document.body.appendChild(code);}())`
although I'll probably get cancelled for saying this

**Comment by SealsRock12** [comment]
Xmader's earlier version relies on a dataset that doesn't exist anymore, so unless someone else is hosting those particular IPFS urls, the dataset won't work for the vast majority of scores.

**Comment by RuralAnemone** [comment]
true
although I've never had any issues with it so idk

**Comment by SealsRock12** [comment]
That's very interesting, the top 3 scores I checked don't work with the old script. Could you share a score that does still work?

**Comment by RuralAnemone** [comment]
https://musescore.com/arcandius/mother-3-033-gentle-rain

video: https://ruralanemone.tech/media/video/Untitled_%20Feb%205%202022%2012_44%20PM.mp4

**Comment by PeterNjeim** [comment]
I don't see you downloading MSCZ in that video

> https://musescore.com/arcandius/mother-3-033-gentle-rain
> 
> video: https://ruralanemone.tech/media/video/Untitled_%20Feb%205%202022%2012_44%20PM.mp4

I don't see you downloading MSCZ in that video

**Comment by RuralAnemone** [comment]
OH sorry I didn't think you meant MSCZ
hang one

**Comment by SealsRock12** [comment]
MIDI/PDF/MP3 don't use the dataset, and use the same method in the old script as in the new one

**Comment by RuralAnemone** [comment]
ah
yeah no MSCZs don't work
I feel like I remember the "open in librescore" button working with the old script fairly recently, but I just checked again and it doesn't

so yeah use the new script

also what I thought you meant by the MSCZ/XML files was "what are you going to use them for"
sorry for the misunderstanding!

**Comment by PeterNjeim** [comment]
lol, MSCZ files are the most sought after files, that's why the app is so popular. MSCZ files are "mother of all files", capable of being openeed in the MuseScore app and converted to any other file type

**Comment by PeterNjeim** [comment]
> also what I thought you meant by the MSCZ/XML files was "what are you going to use them for" (not "how will you download them") sorry for the misunderstanding!

He was actually saying "how will you use them on a Chromebook"
